export default {
  export_calendar_content : "We understand you have a calendar you already use and like. Send your Sylabilt calendar to your email below.",
  text_email : 'Email',
  text_export : 'Export',
  text_cancel : 'Canel',
  text_download_version : 'Download PDF Version',
  text_or : 'Or..',
  heading_error_export : "We apologize!\nThis feature is only available for\nGo 4.0 Subscriptions",
  alertdialog_heading_export : "Oops. We're sorry this feature is only available with Go 4.0 Subscription. $3.99",
  alertdialog_text : "This is a one time fee, SylaBilt doesn’t believe in hassling users with Subscriptions/Cancelling.",
  book_title : "Title : ",
  book_isbn : "ISBN : ",
  book_author : "Author : ",
  book_year  : "Year :",
  book_price : "Price :",
  text_buy : "Buy",
  text_rent : "Rent",
  text_sell : "Sell",
  text_ebook : "EBook",
  text_friends : "Friends",
  text_add_friend : "Add Friends",
  text_app_title : "Sylabilt",
  text_mysyllabi : "MySyllabi",
  text_isbnbook_deals : "Sylabilt Student Saver",
  text_subscribe : "Subscribe",
  text_edit_profile : "Edit Profile",
  text_export_calendar : "Export Calendar",
  text_share_app : "Share App",
  text_settings : "Settings",
  text_login : "Login",
  text_logout : "Logout",
  text_add_meeting : "Add Group Meeting",
  text_add_class : "Add Class",
  text_forgot_password : "Forgot Password"
}
